### ISSUE TITLE
Mixed language

### ISSUE THREAD

**Issue by micker** [elecoest/Manifest2MD#12]
hello i dont understand why i have mixed language in MD
http://www.com3elles.us/com3elles.net/kickflexi/documentation/docs/flexicontent/modules/mod_flexigooglemap.html

**Comment by elecoest** [comment]
je pense que tu as laisser le template par défaut (donc zones vides) et comme le template par défaut est en anglais...

**Comment by micker** [comment]
Faudra que je test

Le 25 mai 2017 à 08:24, à 08:24, Emmanuel Lecoester <notifications@github.com> a écrit:
