### ISSUE TITLE
sql error after component update

### ISSUE THREAD

**Issue by jbreeding** [elecoest/Manifest2MD#7]
` Unknown column 'a.catid' in 'on clause' Unknown column 'a.catid' in 'on clause'`

I also try to uninstall / install the new component, but not better.

/var/log/Apache2/error.log
`Invalid argument supplied for foreach() in /var/www/html/joomla370/joomla-cms/administrator/components/com_manifest2md/models/extensions.php on line 61`

**Comment by jbreeding** [comment]
Bug found:

manifest2md_extensions: bad field name 'category'.
must be changed to 'catid'.

`ALTER TABLE `#__manifest2md_extensions` CHANGE `category` `catid` INT(11) NOT NULL;`

**Comment by elecoest** [comment]
yes :)

fixed in next :)

2017-05-07 10:18 GMT+02:00 Marc Letouzé <notifications@github.com>:
