### ISSUE TITLE
Update Server Not Found

### ISSUE THREAD

**Issue by jbreeding** [elecoest/Manifest2MD#8]
Zip file not present on the Update Server.
`    <updateservers>
        <server type="extension" priority="1" name="Manifest2md Update Server">
            https://github.com/elecoest/AE2MD/archive/manifest2md_update.xml
        </server>
    </updateservers>
`

**Comment by elecoest** [comment]
je vais devoir modifier le Update Server : maintenant c'est Manifest2MD
